using System.Collections.Generic;

namespace Cdln.School.People.Uwp.Lists
{
    public class PhilippineCitiesAndMunicipalitiesList
    {
        public IEnumerable<string> CitiesAndMunicipalities => citiesAndMunicipalities;

        private static readonly IEnumerable<string> citiesAndMunicipalities = new List<string>()
        {
            "Aborlan", "Abra De Ilog", "Abucay", "Abulug", "Abuyog", "Adams", "Agdangan", "Aglipay", "Agno", "Agoncillo", "Agoo", "Aguilar",
            "Aguinaldo", "Agutaya", "Ajuy", "Akbar", "Al-Barka", "Alabat", "Alabel", "Alamada", "Alaminos", "Alangalang", "Albuera", "Alburquerque",
            "Alcala", "Alcantara", "Alcoy", "Alegria", "Aleosan", "Alfonso Castaneda", "Alfonso Lista", "Alfonso", "Aliaga", "Alicia", "Alilem",
            "Alimodian", "Alitagtag", "Allacapan", "Allen", "Almagro", "Almeria", "Aloguinsan", "Aloran", "Altavas", "Alubijid", "Amadeo",
            "Amai Manabilang (Bumbaran)", "Ambaguio", "Amlan", "Ampatuan", "Amulung", "Anahawan", "Anao", "Anda", "Angadanan", "Angat", "Angono",
            "Anilao", "Anini-Y", "Antequera", "Antipas", "Apalit", "Aparri", "Araceli", "Arakan", "Arayat", "Argao", "Aringay", "Aritao",
            "Aroroy", "Arteche", "Asingan", "Asipulo", "Asturias", "Asuncion", "Atimonan", "Atok", "Aurora", "Aurora", "Ayungon", "Baao",
            "Babatngon", "Bacacay", "Bacarra", "Baclayon", "Bacnotan", "Baco", "Bacolod", "Bacolod-Kalawi", "Bacolor", "Bacong", "Bacuag",
            "Badian", "Badiangan", "Badoc", "Bagabag", "Bagac", "Bagamanoc", "Baganga", "Baggao", "Bagulin", "Bagumbayan", "Bakun", "Balabac",
            "Balabagan", "Balagtas", "Balamban", "Balangiga", "Balangkayan", "Balaoan", "Balasan", "Balatan", "Balayan", "Balbalan", "Baleno",
            "Baler", "Balete", "Baliangao", "Baliguian", "Balilihan", "Balindong", "Balingasag", "Balingoan", "Baliuag", "Ballesteros", "Baloi",
            "Balud", "Balungao", "Bamban", "Bambang", "Banate", "Banaue", "Banaybanay", "Banayoyo", "Banga", "Bangar", "Bangued", "Bangui",
            "Banguingui", "Bani", "Banisilan", "Banna", "Bansalan", "Bansud", "Bantay", "Bantayan", "Banton", "Baras", "Barbaza", "Barcelona",
            "Barili", "Barira", "Barlig", "Barobo", "Barotac Nuevo", "Barotac Viejo", "Baroy", "Barugo", "Basay", "Basco", "Basey", "Basilisa",
            "Basista", "Basud", "Batad", "Batan", "Bataraza", "Bato", "Batuan", "Bauan", "Bauang", "Bauko", "Baungon", "Bautista", "Bay", "Bayabas",
            "Bayambang", "Bayang", "Bayog", "Bayombong", "Belison", "Benito Soliven", "Besao", "Bien Unido", "Bilar", "Biliran", "Binalbagan",
            "Binalonan", "Binangonan", "Bindoy", "Bingawan", "Binidayan", "Binmaley", "Binuangan", "Biri", "Boac", "Bobon", "Bocaue", "Bokod",
            "Bolinao", "Boliney", "Boljoon", "Bombon", "Bongabon", "Bongabong", "Bongao", "Bonifacio", "Bontoc", "Borbon", "Boston", "Botolan",
            "Braulio E. Dujali", "Brooke's Point", "Buadiposo-Buntong", "Bubong", "Bucay", "Bucloc", "Buenavista", "Bugallon", "Bugasong", "Buguey",
            "Buguias", "Buhi", "Bula", "Bulacan", "Bulakan", "Bulalacao", "Bulan", "Buldon", "Buluan", "Bulusan", "Bunawan", "Burauen", "Burdeos",
            "Burgos", "Buruanga", "Bustos", "Busuanga", "Butig", "Buug", "Caba", "Cabagan", "Cabangan", "Cabanglasan", "Cabarroguis", "Cabatuan",
            "Cabiao", "Cabucgayan", "Cabugao", "Cabusao", "Cagayancillo", "Cagdianao", "Cagwait", "Caibiran", "Cainta", "Cajidiocan", "Calabanga",
            "Calaca", "Calamba", "Calanasan", "Calanogas", "Calape", "Calasiao", "Calatagan", "Calatrava", "Calauag", "Calauan", "Calayan", "Calbiga",
            "Calendola", "Calinog", "Calintaan", "Calubian", "Calumpit", "Caluya", "Camalaniugan", "Camalig", "Camaligan", "Camiling", "Can-Avid",
            "Canaman", "Candaba", "Candelaria", "Candijay", "Candoni", "Cantilan", "Caoayan", "Capalonga", "Capas", "Capoocan", "Capul", "Caraga",
            "Caramoan", "Caramoran", "Carasi", "Cardona", "Carigara", "Carles", "Carmen", "Carmona", "Carranglan", "Carrascal", "Casiguran", "Castilla",
            "Castillejos", "Cataingan", "Catanauan", "Catarman", "Cateel", "Catigbian", "Catmon", "Catubig", "Cauayan", "Cavinti", "Cawayan",
            "Cervantes", "Chrysanthemum", "Clarin", "Claver", "Claveria", "Columbio", "Compostela", "Concepcion", "Conner", "Consolacion", "Corcuera",
            "Cordon", "Cordova", "Corella", "Coron", "Cortes", "Cuartero", "Cuenca", "Culaba", "Culasi", "Culion", "Currimao", "Cuyab", "Cuyapo",
            "Cuyo", "Daanbantayan", "Daet", "Dagami", "Dagohoy", "Daguioman", "Dalaguete", "Damulog", "Danao", "Dangcagan", "Danglas", "Dao",
            "Dapa", "Daraga", "Daram", "Dasol", "Datu Abdullah Sangki", "Datu Anggal Midtimbang", "Datu Blah T. Sinsuat", "Datu Hoffer Ampatuan",
            "Datu Odin Sinsuat", "Datu Paglas", "Datu Piang", "Datu Saudi-Ampatuan", "Datu Unsay", "Dauin", "Dauis", "Del Carmen", "Del Gallego",
            "Delfin Albano", "Diadi", "Diffun", "Dilasag", "Dimasalang", "Dimataling", "Dimiao", "Dinagat", "Dinalungan", "Dinalupihan", "Dinapigue",
            "Dinas", "Dingalan", "Dingle", "Dingras", "Dipaculao", "Diplahan", "Ditsaan-Ramain", "Divilacan", "Dolores", "Don Carlos", "Don Marcelino",
            "Don Victoriano Chiongbian", "Donsol", "Doña Remedios Trinidad", "Duero", "Dueñas", "Dulag", "Dumalag", "Dumalinao", "Dumalneg",
            "Dumangas", "Dumanjug", "Dumaran", "Dumarao", "Dumingag", "Dupax Del Norte", "Dupax Del Sur", "Echague", "El Nido", "Enrile",
            "Enrique B. Magalona", "Enrique Villanueva", "Esperanza", "Estancia", "Estrella", "Famy", "Fatima", "Ferrol", "Flora",
            "Floridablanca", "G.S.I.S.", "Gabaldon", "Gainza", "Galimuyod", "Gamay", "Gamu", "Ganassi", "Gandara", "Garchitorena",
            "Garcia Hernandez", "Gasan", "Gattaran", "Gen. Emilio Aguinaldo", "Gen. Mariano Alvarez", "Gen. S. K. Pendatun", "General Luna",
            "General Macarthur", "General Mamerto Natividad", "General Nakar", "General Tinio", "General Trias", "Gerona", "Getafe", "Gigaquit",
            "Gigmoto", "Ginatilan", "Giporlos", "Gitagum", "Glan", "Gloria", "Goa", "Godod", "Gonzaga", "Governor Generoso", "Gregorio Del Pilar",
            "Guagua", "Gubat", "Guiguinto", "Guimba", "Guimbal", "Guinayangan", "Guindulman", "Guindulungan", "Guinobatan", "Guinsiliban",
            "Guipos", "Guiuan", "Gumaca", "Gutalac", "Hadji Mohammad Ajul", "Hadji Muhtamad", "Hadji Panglima Tahil", "Hagonoy", "Hamtic",
            "Hermosa", "Hernani", "Hilongos", "Hinabangan", "Hinatuan", "Hindang", "Hingyon", "Hinigaran", "Hinoba-An", "Hinunangan", "Hinundayan",
            "Hungduan", "Iba", "Ibaan", "Ibajay", "Igbaras", "Iguig", "Ilog", "Imelda", "Impasug-ong", "Inabanga", "Indanan", "Indang", "Infanta",
            "Initao", "Inopacan", "Ipil", "Irosin", "Isabel", "Isabela", "Isulan", "Itbayat", "Itogon", "Ivana", "Ivisan", "Jabonga", "Jaen",
            "Jagna", "Jala-Jala", "Jamindan", "Janiuay", "Jaro", "Jasaan", "Javier", "Jiabong", "Jimalalud", "Jimenez", "Jipapad", "Jolo", "Jomalig",
            "Jones", "Jordan", "Jose Abad Santos (Trinidad)", "Jose Abad Santos", "Jose Dalman", "Jose Panganiban", "Josefina", "Jovellar", "Juban",
            "Julita", "Kabacan", "Kabasalan", "Kabayan", "Kabugao", "Kabuntalan", "Kadingilan", "Kalamansig", "Kalawit", "Kalayaan", "Kalibo",
            "Kalilangan", "Kalingalan Caluang", "Kananga", "Kapai", "Kapalong", "Kapangan", "Kapatagan", "Kasibu", "Katipunan", "Kauswagan",
            "Kawayan", "Kawit", "Kayapa", "Kiamba", "Kiangan", "Kibawe", "Kiblawan", "Kibungan", "Kinoguitan", "Kitaotao", "Kitcharao",
            "Kolambugan", "Kumalarang", "La Castellana", "La Libertad", "La Paz", "La Trinidad", "Laak", "Labangan", "Labason", "Labo",
            "Labrador", "Lacub", "Lagangilang", "Lagawe", "Lagayan", "Lagonglong", "Lagonoy", "Laguindingan", "Lake Sebu", "Lakewood",
            "Lal-Lo", "Lala", "Lambayong", "Lambunao", "Lamut", "Landayan", "Langgam", "Langiden", "Languyan", "Lantapan", "Lantawan",
            "Lanuza", "Laoac", "Laoang", "Lapinig", "Lapuyan", "Laram", "Larena", "Las Navas", "Las Nieves", "Lasam", "Laua-An", "Laur",
            "Laurel", "Lavezares", "Lawaan", "Lazi", "Lebak", "Leganes", "Lemery", "Leon B. Postigo (Bacungan)", "Leon", "Leyte", "Lezo",
            "Lian", "Lianga", "Libacao", "Libagon", "Libertad", "Libjo", "Libmanan", "Libon", "Libona", "Libungan", "Licab", "Licuan-Baay",
            "Lidlidda", "Lila", "Liliw", "Liloan", "Liloy", "Limasawa", "Limay", "Linamon", "Linapacan", "Lingayen", "Lingig", "Llanera",
            "Llorente", "Loay", "Lobo", "Loboc", "Looc", "Loon", "Lope De Vega", "Lopez Jaena", "Lopez", "Loreto", "Los Baños", "Luba",
            "Lubang", "Lubao", "Lubuagan", "Lucban", "Lugait", "Lugus", "Luisiana", "Lumba-Bayabao", "Lumbaca-Unayan", "Lumban", "Lumbatan",
            "Lumbayanague", "Luna", "Lupao", "Lupi", "Lupon", "Lutayan", "Luuk", "M'lang", "Ma-Ayon", "Maasim", "Maasin", "Mabinay", "Mabini",
            "Mabitac", "Mabuhay", "Macabebe", "Macalelon", "Macarthur", "Maco", "Maconacon", "Macrohon", "Madalag", "Madalum", "Madamba",
            "Maddela", "Madrid", "Madridejos", "Magalang", "Magallanes", "Magarao", "Magdalena", "Magdiwang", "Magpet", "Magsaysay",
            "Magsingal", "Maguing", "Mahaplag", "Maharlika", "Mahatao", "Mahayag", "Mahinog", "Maigo", "Maimbung", "Mainit", "Maitum",
            "Majayjay", "Makato", "Makilala", "Malabang", "Malabuyoc", "Malalag", "Malangas", "Malapatan", "Malasiqui", "Malay", "Malibcong",
            "Malilipot", "Malimono", "Malinao", "Malita", "Malitbog", "Mallig", "Malungon", "Maluso", "Malvar", "Mamasapano", "Mambajao",
            "Mamburao", "Mambusao", "Manabo", "Manaoag", "Manapla", "Manay", "Mandaon", "Mangaldan", "Mangatarem", "Mangudadatu", "Manito",
            "Manjuyod", "Mankayan", "Manolo Fortich", "Mansalay", "Manticao", "Manukan", "Mapanas", "Mapandan", "Mapun", "Marabut", "Maragondon",
            "Maragusan", "Maramag", "Marantao", "Marcos", "Margosatubig", "Maria Aurora", "Maria", "Maribojoc", "Marihatag", "Marilao",
            "Maripipi", "Mariveles", "Marogong", "Masantol", "Masinloc", "Masiu", "Maslog", "Mataas Na Kahoy", "Mataasnakahoy", "Matag-Ob",
            "Matalam", "Matalom", "Matanao", "Matanog", "Matnog", "Matuguinao", "Matungao", "Mauban", "Mawab", "Mayantoc", "Maydolong",
            "Mayorga", "Mayoyao", "Medellin", "Medina", "Mendez", "Mercedes", "Merida", "Mexico", "Miagao", "Midsalip", "Midsayap", "Milagros",
            "Milaor", "Mina", "Minalabac", "Minalin", "Minglanilla", "Moalboal", "Mobo", "Mogpog", "Moises Padilla", "Molave", "Moncada",
            "Mondragon", "Monkayo", "Monreal", "Montevista", "Morong", "Motiong", "Mulanay", "Mulondo", "Munai", "Murcia", "Mutia", "Naawan",
            "Nabas", "Nabua", "Nabunturan", "Naga", "Nagbukel", "Nagcarlan", "Nagtipunan", "Naguilian", "Naic", "Nampicuan", "Narra",
            "Narvacan", "Nasipit", "Nasugbu", "Natividad", "Natonin", "Naujan", "Naval", "New Bataan", "New Corella", "New Lucena",
            "New Washington", "Norala", "Northern Kabuntalan", "Norzagaray", "Noveleta", "Nueva Era", "Nueva Valencia", "Nueva", "Numancia",
            "Nunungan", "Oas", "Obando", "Ocampo", "Odiongan", "Old Panamao", "Olutanga", "Omar", "Opol", "Orani", "Oras", "Orion", "Oslob",
            "Oton", "Pacita 1", "Pacita 2", "Padada", "Padre Burgos", "Padre Garcia", "Paete", "Pagagawan", "Pagalungan", "Pagayawan", "Pagbilao",
            "Paglat", "Pagsanghan", "Pagsanjan", "Pagudpud", "Pakil", "Palanan", "Palanas", "Palapag", "Palauig", "Palimbang", "Palo", "Palompon",
            "Paluan", "Pambujan", "Pamplona", "Panaon", "Panay", "Pandag", "Pandami", "Pandan", "Pandi", "Panganiban", "Pangantucan", "Pangil",
            "Panglao", "Panglima Estino", "Panglima Sugala", "Pangutaran", "Paniqui", "Panitan", "Pantabangan", "Pantao Ragat", "Pantar",
            "Pantukan", "Panukulan", "Paoay", "Paombong", "Paracale", "Paracelis", "Paranas", "Parang", "Pasacao", "Pasil", "Pastrana", "Pasuquin",
            "Pata", "Pateros City", "Patikul", "Patnanungan", "Patnongon", "Pavia", "Payao", "Perez", "Peñablanca", "Peñaranda", "Peñarrubia",
            "Piagapo", "Piat", "Picong", "Piddig", "Pidigan", "Pigkawayan", "Pikit", "Pila", "Pilar", "Pili", "Pililla", "Pinabacdao", "Pinamalayan",
            "Pinamungahan", "Pinan", "Pinili", "Pintuyan", "Pinukpuk", "Pio Duran", "Pio V. Corpuz", "Pitogo", "Placer", "Plaridel", "Poblacion", "Pola",
            "Polanco", "Polangui", "Polillo", "Polomolok", "Pontevedra", "Poona Bayabao", "Poona Piagapo", "Porac", "Poro", "Pototan", "Pozzorubio",
            "Pres. Carlos P. Garcia", "Pres. Manuel Roxas", "Presentacion", "President Quirino", "President Roxas", "Prieto Diaz", "Prosperidad",
            "Pualas", "Pudtol", "Puerto Galera", "Pugo", "Pulilan", "Pulupandan", "Pura", "Quezon", "Quinapondan", "Quirino", "Ragay", "Rajah Buayan",
            "Ramon Magsaysay", "Ramon", "Ramos", "Rapu-Rapu", "Real", "Reina Mercedes", "Remedios T. Romualdez", "Riverside", "Rizal", "Rodriguez",
            "Romblon", "Ronda", "Rosales", "Rosario", "Roseller T. Lim", "Roxas", "Sabangan", "Sablan", "Sablayan", "Sabtang", "Sadanga", "Sagada",
            "Sagay", "Sagbayan", "Saguday", "Saguiaran", "Sagñay", "Saint Bernard", "Salay", "Salcedo", "Sallapadan", "Salug", "Salvador Benedicto",
            "Salvador", "Samal", "Samboan", "Sampaguita Village", "Sampaloc", "San Agustin", "San Andres", "San Antonio", "San Benito", "San Clemente",
            "San Dionisio", "San Emilio", "San Enrique", "San Esteban", "San Fabian", "San Felipe", "San Fernando", "San Francisco", "San Gabriel",
            "San Guillermo", "San Ildefonso", "San Isidro", "San Jacinto", "San Joaquin", "San Jorge", "San Jose De Buan", "San Jose", "San Juan",
            "San Julian", "San Leonardo", "San Lorenzo Ruiz", "San Lorenzo", "San Luis", "San Manuel", "San Marcelino", "San Mariano", "San Mateo",
            "San Miguel", "San Narciso", "San Nicolas", "San Pablo", "San Pascual", "San Pedro", "San Policarpo", "San Quintin", "San Rafael",
            "San Remigio", "San Ricardo", "San Roque", "San Sebastian", "San Simon", "San Teodoro", "San Vicente", "Sanchez-Mira", "Santa Ana",
            "Santa Barbara", "Santa Catalina", "Santa Cruz", "Santa Elena", "Santa Fe", "Santa Ignacia", "Santa Josefa", "Santa Lucia", "Santa Magdalena",
            "Santa Marcela", "Santa Margarita", "Santa Maria", "Santa Monica", "Santa Praxedes", "Santa Rita", "Santa Rosa", "Santa Teresita",
            "Santa", "Santander", "Santiago", "Santo Domingo", "Santo Niño", "Santo Tomas", "Santol", "Sapa-Sapa", "Sapad", "Sapang Dalaga",
            "Sapi-An", "Sara", "Sarangani", "Sariaya", "Sarrat", "Sasmuan", "Sebaste", "Sen. Ninoy Aquino", "Sergio Osmena Sr.", "Sevilla",
            "Shariff Aguak", "Shariff Saydona Mustapha", "Siasi", "Siaton", "Siay", "Siayan", "Sibagat", "Sibalom", "Sibonga", "Sibuco",
            "Sibulan", "Sibunag", "Sibutad", "Sibutu", "Sierra Bullones", "Sigay", "Sigma", "Sikatuna", "Silago", "Silang", "Silvino Lobos",
            "Simunul", "Sinacaban", "Sinait", "Sindangan", "Siniloan", "Siocon", "Sipocot", "Siquijor", "Sirawai", "Siruma", "Sison", "Sitangkai",
            "Socorro", "Sofronio Española", "Sogod", "Solana", "Solano", "Solsona", "Sominot", "South Ubian", "South Upi", "Sual", "Subic",
            "Sudipen", "Sugbongcogon", "Sugpon", "Sulat", "Sulop", "Sultan Dumalondong", "Sultan Kudarat", "Sultan Mastura", "Sultan Naga Dimaporo",
            "Sultan Sa Barongis", "Sultan Sumagka", "Sumilao", "Sumisip", "Surallah", "Suyo", "T'boli", "Taal", "Tabango", "Tabina", "Tabogon",
            "Tabontabon", "Tabuan-Lasa", "Tabuelan", "Tadian", "Taft", "Tagana-An", "Tagapul-An", "Tagbina", "Tagkawayan", "Tago", "Tagoloan II",
            "Tagoloan", "Tagudin", "Talacogon", "Talaingod", "Talakag", "Talalora", "Talavera", "Talayan", "Talibon", "Talipao", "Talisay",
            "Talisayan", "Talugtug", "Talusan", "Tambulig", "Tampakan", "Tamparan", "Tampilisan", "Tanauan", "Tanay", "Tandubas", "Tangalan",
            "Tangcal", "Tantangan", "Tanudan", "Tanza", "Tapaz", "Tapul", "Taraka", "Tarangnan", "Tarragona", "Tayasan", "Taysan", "Taytay", "Tayug",
            "Tayum", "Teresa", "Ternate", "Tiaong", "Tibiao", "Tigaon", "Tigbao", "Tigbauan", "Tinambac", "Tineg", "Tinglayan", "Tingloy", "Tinoc",
            "Tipo-Tipo", "Titay", "Tiwi", "Tobias Fornier", "Toboso", "Tolosa", "Tomas Oppus", "Torrijos", "Trento", "Trinidad", "Tuao", "Tuba",
            "Tubajon", "Tubao", "Tubaran", "Tubay", "Tubigon", "Tublay", "Tubo", "Tubod", "Tubungan", "Tuburan", "Tudela", "Tugaya", "Tukuran",
            "Tulunan", "Tumauini", "Tunga", "Tungawan", "Tupi", "Turtle Islands", "Tuy", "Ubay", "Umingan", "Ungkaya Pukan", "Unisan", "United Bayanihan",
            "United Better Living", "Upi", "Urbiztondo", "Uson", "Uyugan", "Valderrama", "Valencia", "Valladolid", "Vallehermoso", "Veruela",
            "Victoria", "Viga", "Villaba", "Villanueva", "Villareal", "Villasis", "Villaverde", "Villaviciosa", "Vincenzo A. Sagun", "Vintar",
            "Vinzons", "Virac", "Wao", "Zamboanguita", "Zambowood", "Zaragoza", "Zarraga", "Zumarraga",

            "Alaminos City", "Angeles City", "Antipolo City", "Bacolod City", "Bacoor City", "Bago City", "Baguio City", "Bais City",
            "Balanga City", "Batac City", "Batangas City", "Bayawan City", "Baybay City", "Bayugan City", "Biñan City", "Bislig City",
            "Bogo City", "Borongan City", "Butuan City", "Cabadbaran City", "Cabanatuan City", "Cabuyao City", "Cadiz City", "Cagayan de Oro City",
            "Calamba City", "Calapan City", "Calbayog City", "Caloocan City", "Candon City", "Canlaon City", "Carcar City", "Catbalogan City",
            "Cauayan City", "Cavite City", "Cebu City", "Cotabato City", "Dagupan City", "Danao City", "Dapitan City", "Dasmariñas City", "Davao City",
            "Digos City", "Dipolog City", "Dumaguete City", "El Salvador City", "Escalante City", "Gapan City", "General Santos City", "General Trias City",
            "Gingoog City", "Guihulngan City", "Himamaylan City", "Ilagan City", "Iligan City", "Iloilo City", "Imus City", "Iriga City", "Isabela City",
            "Kabankalan City", "Kidapawan City", "Koronadal City", "La Carlota City", "Lamitan City", "Laoag City", "Lapu Lapu City", "Las Piñas City",
            "Legazpi City", "Ligao City", "Lipa City", "Lucena City", "Maasin City", "Mabalacat City", "Makati City", "Malabon City", "Malaybalay City",
            "Malolos City", "Mandaluyong City", "Mandaue City", "Manila City", "Marawi City", "Marikina City", "Masbate City", "Mati City", "Meycauayan City",
            "Muñoz City", "Muntinlupa City", "Naga City", "Navotas City", "Olongapo City", "Ormoc City", "Oroquieta City", "Ozamiz City", "Pagadian City",
            "Palayan City", "Panabo City", "Parañaque City", "Pasay City", "Pasig City", "Passi City", "Puerto Princesa City", "Quezon City", "Roxas City",
            "Sagay City", "Samal City", "San Carlos City", "San Fernando City", "San Jose City", "San Jose del Monte City", "San Juan City", "San Pablo City",
            "San Pedro City", "Santo Tomas City", "Santa Rosa City", "Santiago City", "Silay City", "Sipalay City", "Sorsogon City", "Surigao City",
            "Tabaco City", "Tabuk City", "Tacloban City", "Tacurong City", "Tagaytay City", "Tagbilaran City", "Taguig City", "Tagum City", "Talisay City",
            "Tanauan City", "Tandag City", "Tangub City", "Tanjay City", "Tarlac City", "Tayabas City", "Toledo City", "Trece Martires City", "Tuguegarao City",
            "Urdaneta City", "Valencia City", "Valenzuela City", "Victorias City", "Vigan City", "Zamboanga City"
        };
    }
}
